export const ADD_PLAYER = 'ADD_PLAYER';
export const SHUFFLE_PLAYERS = 'SHUFFLE_PLAYERS';
export const CLEAR_PLAYERS = 'CLEAR_PLAYERS';
export const INCREMENT_PLAYER_INDEX = 'INCREMENT_PLAYER_INDEX';
export const PASS_PLAYER = 'PASS_PLAYER';
